apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: team08registry.azurecr.io/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: DB_URL_ORDER
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: DB_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: order-kafka-secret
                  key: CONNECTION_STRING
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: AZURE_STORAGE_ACCOUNT_KEY
